apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "feab.fullname" . }}
  namespace: {{ .Values.image.namespace }}
  labels:
    app: {{ template "feab.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas:  {{ .Values.image.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "feab.fullname" . }}
    spec:
     {{ if .Values.serviceAccount.create -}}
      serviceAccountName: {{ template "feab.serviceAccountName" .}}
    {{ end -}}
      containers:
      - name: {{ template "feab.fullname" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: BUCKET
            value: {{ .Values.feab.bucket }}
          - name: FALCO_ENDPOINT
            value: {{ .Values.feab.falco_ep }}
          - name: AWS_DEFAULT_REGION
            value: {{ .Values.feab.aws_region }}
